export const GATEWAY_AUTH_SERVICE = "GATEWAY_AUTH_SERVICE";
export const GATEWAY_TICKET_SERVICE = "GATEWAY_TICKET_SERVICE";
export const GATEWAY_TRAIN_SERVICE = "GATEWAY_TRAIN_SERVICE";
export const GATEWAY_NOTIFICATION_SERVICE = "GATEWAY_NOTIFICATION_SERVICE"
export const GATEWAY_CHAT_SERVICE = "GATEWAY_CHAT_SERVICE"